config/routes.rb
Rails.application.routes.draw do
  # get my root route
  root to: "main#index"

  # other pages
  get "about-us", to: "about#index", as: :about

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
      @image_urls = [
        'https://images.pexels.com/photos/18133948/pexels-photo-18133948/free-photo-of-portrait-of-woman-in-traditional-clothing-and-hat.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'https://images.pexels.com/photos/26987191/pexels-photo-26987191/free-photo-of-processed-with-vsco-with-m5-preset.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load'
      ]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
hi i am bitch

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Treiven - Pastries Order Now!</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap" rel="stylesheet">
    <%= favicon_link_tag asset_path('trv.png') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>

  <%= render partial: "shared/navbar" %>
  <main class="treiven-container">
    <%= yield %>
  </main>
  </body>
</html>

app/views/main/index.html.erb
<main class="body-content">
        <div class="search-wrapper">
            <input type="text" id="search-input" maxlength="60" placeholder="Search...">
            <button type="submit">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18">
                    <g fill="#ffffff" class="nc-icon-wrapper">
                        <line x1="15.25" y1="15.25" x2="11.285" y2="11.285" fill="none" stroke="#ffffff" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" data-color="color-2"></line>
                        <circle cx="7.75" cy="7.75" r="5" fill="none" stroke="#ffffff " stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></circle>
                    </g>
                </svg>
            </button>
        </div>
        <div class="tab-wrapper">
            <div class="tab-group tab-active">
                <%= image_tag 'tab-groups/treiven-biscuit.svg', alt: 'Treiven Biscuit' %>
                <span>Cookies</span>
            </div>
            <div class="tab-group tab">
                <%= image_tag 'tab-groups/treiven-brownie.svg', alt: 'Treiven Brownies' %>
                <span>Brownies</span>
            </div>
            <div class="tab-group tab">
                <%= image_tag 'tab-groups/treiven-cake.svg', alt: 'Treiven Cakes' %>
                <span>Cakes</span>
            </div>
            <div class="tab-group tab">
                <%= image_tag 'tab-groups/treiven-specialty.svg', alt: 'Treiven Specialty' %>
                <span>Specialty</span>
            </div>
        </div>
        <div class="grid-items-container">
            <div class="grid-items-wrapper">
                <% @image_urls.each do |image_url| %>
                <a href="" class="treiven-items">
                    <div class="treiven-pics">
                    <%= image_tag image_url, alt: 'Treiven Specialty' %>
                    </div>
                    <div class="treiven-infos">
                        <div class="treiven-product">
                            <span>So hot baby ruby when</span>
                            <p class="treiven-badge">Specials</p>
                        </div>
                        <div class="treiven-product-price">
                            <span>₱500.00</span>
                            <p class="avail-stocks">Available</p>
                        </div>
                    </div>
                </a>
                <% end %>
            </div>
        </div>
    </main>

app/views/shared/_navbar.html.erb
<header class="nav-container">
    <nav class="nav-wrapper">
        <div class="nav-logo">
            <a href="./">
                <img src="/images/trieven.svg" alt="" />
            </a>
        </div>
        <ul class="nav-link-wrapper">
            <li class="nav-links">
                <%= link_to 'Explore' , root_path %>
            </li>
            <li class="nav-links">
                <%= link_to 'About' , about_path %>
            </li>
        </ul>
        <div class="right-side-wrapper">
            <div class="modal-info">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18">
                    <g fill="#212121" class="nc-icon-wrapper">
                        <line x1="13.25" y1="5.25" x2="16.25" y2="5.25" fill="none" stroke="#212121"
                            stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"></line>
                        <line x1="1.75" y1="5.25" x2="8.75" y2="5.25" fill="none" stroke="#212121"
                            stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"></line>
                        <circle cx="11" cy="5.25" r="2.25" fill="none" stroke="#212121" stroke-linecap="round"
                            stroke-linejoin="round" stroke-width="1.5"></circle>
                        <line x1="4.75" y1="12.75" x2="1.75" y2="12.75" fill="none" stroke="#212121"
                            stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" data-color="color-2">
                        </line>
                        <line x1="16.25" y1="12.75" x2="9.25" y2="12.75" fill="none" stroke="#212121"
                            stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" data-color="color-2">
                        </line>
                        <circle cx="7" cy="12.75" r="2.25" fill="none" stroke="#212121" stroke-linecap="round"
                            stroke-linejoin="round" stroke-width="1.5" data-color="color-2"></circle>
                    </g>
                </svg>
            </div>
            <div class="auth-user-options">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18">
                    <g fill="#212121" class="nc-icon-wrapper">
                        <circle cx="9" cy="4.5" r="2.75" fill="none" stroke="#212121" stroke-linecap="round"
                            stroke-linejoin="round" stroke-width="1.5" data-color="color-2"></circle>
                        <path
                            d="M13.762,15.516c.86-.271,1.312-1.221,.947-2.045-.97-2.191-3.159-3.721-5.709-3.721s-4.739,1.53-5.709,3.721c-.365,.825,.087,1.774,.947,2.045,1.225,.386,2.846,.734,4.762,.734s3.537-.348,4.762-.734Z"
                            fill="none" stroke="#212121" stroke-linecap="round" stroke-linejoin="round"
                            stroke-width="1.5"></path>
                    </g>
                </svg>
            </div>``
        </div>
        <div class="modal-option-wrapper" style="display: none; opacity: 0;">
            <li class="modal-links">
                <a href="">Sign up</a>
            </li>
            <li class="modal-links">
                <a href="">Sign in</a>
            </li>
            <li class="modal-links">
                <a href="" target="_blank">GitHub Repository</a>
            </li>
        </div>
    </nav>
</header>